name: Deploy to Artifact Registry

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Define repository host
        env:
          REPO_HOST: australia-southeast2-docker.pkg.dev

      - name: Configure Docker
        run: |-
          gcloud auth configure-docker $REPO_HOST

      - name: Define image tag
        env:
          IMAGE_TAG: $REPO_HOST/${{ secrets.GCP_PROJECT_ID }}/mysampleapp/myapp

      - name: Build and push image to Google Artifact Registry
        run: |-
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
